matrix-org/vodozemac

- src/sas.rs
Methods that take self can't easily be bound over FFI, since the
intetion of this crate is to work in various languages let's switch to a
method that takes a borrow of self.
This is a bit unfortunate since we do not want people to reuse the
secret key here.
> Use a ReusableSecret for the Sas curve25519 secret key

- src/sas.rs
We switched to using a ReusableSecret due to FFI reasons, but some language binding libs support taking self and those that do not can easily wrap the vodozemac Sas object in an Option.
This reverts commit 6976cca186cbf04061cfa558771f8203fcb11acf.
> Revert "fix(sas): Use a ReusableSecret for the Sas curve25519 secret key"

- README.md
- src/olm/account/mod.rs
- src/olm/messages/mod.rs
- src/olm/mod.rs
- src/olm/session/mod.rs
The API to create an inbound Session in libolm has three distinct steps:
1. Create a Session from a pre-key message
2. Decrypt the pre-key message
3. Remove the one-time key that was used to create the Session in step 1
This API is a bit problematic since it places the burden on the user to remove used up one-time keys. Furthermore it requires the pre-key message to be decoded twice, once for the Session creation step and once
for the decryption step.
vodozemac removed problem one by removing the one-time key when the Session has been created. This creates another problem, it lets users remove private one-time keys from our pool without actually using them
up. The user can create a Session on our side without ever producing a valid encrypted message for the Session.
This in turn results …
> fix(olm): Decrypt the message when we create an inbound Session

- src/lib.rs
- src/megolm/group_session.rs
- src/megolm/inbound_group_session.rs
- src/megolm/message.rs
- src/olm/account/mod.rs
- src/types/curve25519.rs
- src/types/ed25519.rs
- src/types/mod.rs
This PR makes sure that we don't use ed25519-dalek types directly, instead we use our wrapper types and re-exports.
This comes in handy because we need to convert to/from base64 and we may switch ed25519 libs. It also makes it easy to put the verify/verify_strict method of the ed25519 public keys behind a feature flag.
> Refactor our types an clean up the pickling logic

- src/olm/mod.rs
It's returned by `OlMessage::message_type()`.
> Make `MessageType` public

- src/olm/account/mod.rs
This is useful in rare circumstances where the caller wishes to remove
a one time key that hasn't been used.
> Make `Account::remove_one_time_key` public.

- src/olm/account/one_time_keys.rs
We remove the OTKs from the `public_keys` map once they're published, but we need to keep the entries in `reverse_public_keys` for as long as they're still in `private_keys`.
Not sure if we want to rename `reverse_public_keys`?
> Fix OTK pickling

- src/sas.rs
This PR adds a dedicated MAC type to libolm, useful because Ruma nowadays decodes base64 encoded strings when deserializing. 
It also adds the buggy mac calculation method from libolm, since that one is still widely used.
> Sas libolm compat

- src/types/ed25519.rs
The from_bytes method comes from the Signature trait instead from the type directly.
> Use try_from to create Signature objects

- src/lib.rs
- src/megolm/inbound_group_session.rs
- src/olm/account/mod.rs
- src/sas.rs
- src/types/curve25519.rs
- src/types/ed25519.rs
- src/types/mod.rs
This type is useful if users need to create a separate identity to sign messages with, i.e. it's used in cross signing in Matrix land.
> Add and expose an ed25519 secret key type

- .pre-commit-config.yaml
Without this change, the clippy hook isn't executed correctly.
> Update pre-commit hooks.

- README.md
- src/cipher/mod.rs
- src/lib.rs
- src/megolm/group_session.rs
- src/megolm/inbound_group_session.rs
- src/megolm/mod.rs
- src/megolm/ratchet.rs
- src/olm/account/fallback_keys.rs
- src/olm/account/mod.rs
- src/olm/mod.rs
- src/olm/session/chain_key.rs
- src/olm/session/double_ratchet.rs
- src/olm/session/mod.rs
- src/olm/session_keys.rs
- src/types/curve25519.rs
- src/types/ed25519.rs
- src/types/mod.rs
- src/utilities/libolm_compat.rs
- src/utilities/mod.rs
A lot of types in our serialization logic seem to be of questionable usage. We should revise our serialization logic and where possible remove helper structs and use serde directly, this include error types.
> Simplify our serialization logic

- src/olm/account/fallback_keys.rs
- src/olm/account/mod.rs
- src/olm/account/one_time_keys.rs
- src/olm/session/mod.rs
- src/olm/session/ratchet.rs
- src/olm/shared_secret.rs
- src/types/curve25519.rs
- src/types/ed25519.rs
- src/types/mod.rs
- refactor(types): Put the curve25519 secret key type behind a box
- refactor(types): Put the ed25519 secret key types behind a box
> Put secret keys behind a box to avoid unwanted memcpys

- src/lib.rs
- src/megolm/ratchet.rs
This fixes a small issue where it wasn't obvious that our RatchetParts
is using borrowing.
> Enable the rust-2018-idioms lint

- Cargo.toml
- README.md
- src/cipher/mod.rs
- src/hazmat/mod.rs
- src/hazmat/olm.rs
- src/lib.rs
- src/megolm/group_session.rs
- src/megolm/inbound_group_session.rs
- src/megolm/message.rs
- src/olm/messages/pre_key.rs
- src/olm/mod.rs
- src/olm/session/double_ratchet.rs
- src/olm/session/message_key.rs
- src/olm/session/mod.rs
- src/olm/session/ratchet.rs
- src/olm/session_keys.rs
- src/types/ed25519.rs
- src/types/mod.rs
This is so that advanced systems can do non-standard stuff, without exposing those APIs by standard.
> Expose some lower level APIs behind a `low-level` feature flag.

- src/megolm/group_session.rs
- src/megolm/inbound_group_session.rs
- src/megolm/mod.rs
- src/megolm/session_keys.rs
This PR removes the final string wrapper we had. As usual libolm compatible strings can still be easily parsed and created using the `from_base64()` and `to_base64()` methods.
Serialization and deserialization implementations exist and also use the base64 representation.
> Typed megolm session keys

- src/olm/account/mod.rs
- src/olm/mod.rs
- src/olm/session/mod.rs
- src/sas.rs
- src/types/curve25519.rs
- refactor(types): Remove the encoded public key from the curve25519 types
- refactor(sas): Remove the encoded public key methods
- refactor(olm): Remove the encoded one-time keys method
> Remove encoded public key variants of some methods

- src/megolm/group_session.rs
- src/megolm/inbound_group_session.rs
- src/megolm/mod.rs
- src/olm/account/mod.rs
- src/olm/mod.rs
- src/olm/session/double_ratchet.rs
- src/olm/session/mod.rs
This is a proposal to allow using bytes directly without extra
conversion steps.
Use case: I am using protobuf encoded messages and encrypt them with
Olm. Now if I want to decrypt an Olm message vodozemac will decrypt the
message convert bytes into string and return it to me. Me, in turn, need
to convert string back into bytes and then decode my protobuf message.
The same thing happens when encoding a message.
What do you think? Current implementation breaks `InboundCreationResult` type for implementation simplicity.
> feat: Expose encrypting and decrypting bytes

- src/olm/account/mod.rs
This method is a low level API, reflect that by putting it behind the low-level-api feature flag.
> fix(olm): Hide the remove_one_time_key method

- .github/workflows/docs.yml
The force_orphan[[1]] option ensures that the branch that is used to publish the docs has only a single commit. This lowers the space that is used by the docs publishing branch.
[1]: https://github.com/marketplace/actions/github-pages-action#%EF%B8%8F-force-orphan-force_orphan
> ci(docs): Enable the force_orphan option

- Cargo.toml
- src/megolm/message.rs
All our other from_bytes methods take slices, so this makes it consistent with the rest of the codebase.
> refactor!(megolm): Change from_bytes to take a slice instead of a vec

- src/olm/messages/pre_key.rs
- src/olm/session/mod.rs
- src/olm/session_keys.rs
This is useful if we want to log the session ID as soon as we find out we have a pre-key message, in the case of the message failing to decrypt we'll still be able to log the expected session ID.
> feat(olm): Add a method to calculate the Session ID from a pre-key message

- src/olm/account/mod.rs
- src/olm/account/one_time_keys.rs
- src/olm/mod.rs
The method to generate new one-time keys silently discards old, and creates new one-time keys. It might be useful to the caller to know that some one-time keys were discarded and to see which ones got newly created.
This patch modifies the method `generate_one_time_keys()` so returns a value showing us which, if any, one-time keys got discarded, and which got created.
> feat!: Return the created and discarded one-time keys when generating new ones

- Cargo.toml
- build.rs
- src/lib.rs
That was a brain fart, we don't upload the git tree to crates.io. We can't reliably know the git commit at build time.
Reverts matrix-org/vodozemac#106
> Revert "Expose the build-time git commit hash and description as static vars"

- .github/workflows/ci.yml
- .github/workflows/coverage.yml
- .github/workflows/docs.yml
Basically all of the `actions-rs/*` actions are unmaintained. See <https://github.com/actions-rs/toolchain/issues/216> for more information. Due to their age they generate several warnings in CI runs, for example in https://github.com/matrix-org/vodozemac/actions/runs/4881349941:
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions-rs/toolchain@v1, actions-rs/cargo@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
To get rid of those warnings the occurrences of `actions-rs/toolchain` are replaced by [`dtolnay/rust-toolchain`](https://github.com/dtolnay/rust-toolchain), and the occurrences of `actions-rs/cargo` are replaced by direct invocations of …
> chore: Replace unmaintained actions-rs/* actions in CI workflow

- src/types/ed25519.rs
We can't anymore get to a slice of bytes from a Ed25519 secret key,
instead we get a copy of the bytes.
This means that our to_base64 method now operates on a copy of the bytes
which we should zeroize.
> Zeroize the bytes when we convert a secret key to base64

- src/lib.rs
- src/megolm/message.rs
Consumers of this crate might need to encode or decode base64 as well. To have a consistent decoding experience they would need to replicate the exact config we're using.
Let's just expose the methods so consumers don't need to think about the exact base64 config to use.
> feat: Expose the base64 decoding and encoding methods

- .typos.toml
Looks like there are currently no such typos here, but it has happened a lot in the SDK so why not check for it here too.
> Detect 'sign'-related typos

- src/olm/session/receiver_chain.rs
The ratchet key is a crucial piece of information when trying to debug a decryption failure of a Olm Session.
The ratchet key and chain index, which are found inside a Olm message, form a pair which uniquely identifies the individual message key that should be used to decrypt the message.
To inspect why a decryption failure occurs it's useful to have the ratchet key and chain index pair, this allows us to double check if the correct chain is part of the Session.
> Add the RatchetKey to the Debug output of the ReceiverChain

- .cargo/mutants.toml
- src/olm/messages/message.rs
Relates to: #78
Fixes the following:
```
MISSED   src/olm/messages/message.rs:63:9: replace Message::version -> u8 with 0 in 0.8s build + 2.8s test
MISSED   src/olm/messages/message.rs:58:9: replace Message::ciphertext -> &[u8] with Vec::leak(vec![1]) in 0.8s build + 3.2s test
MISSED   src/olm/messages/message.rs:58:9: replace Message::ciphertext -> &[u8] with Vec::leak(Vec::new()) in 0.8s build + 3.0s test
MISSED   src/olm/messages/message.rs:63:9: replace Message::version -> u8 with 1 in 0.8s build + 2.8s test
MISSED   src/olm/messages/message.rs:58:9: replace Message::ciphertext -> &[u8] with Vec::leak(vec![0]) in 0.8s build + 2.8s test
MISSED   src/olm/messages/message.rs:53:9: replace Message::chain_index -> u64 with 1 in 0.8s build + 2.8s test
MISSED …
```
> test(olm): Add more tests

- .cargo/mutants.toml
- src/olm/session/message_key.rs
Testing the getters is a bit dull but since they're not actually used anywhere else in the library, this seems like the only way to catch their mutants.
I also excluded all `Drop` mutants because it doesn't look like the zeroisation can be tested in Rust. I tried using raw pointers into the struct fields in a test but the memory didn't end up reliably zeroed – I think because `drop` moves the value which can perform a memory copy.
Relates to: #78
> test(olm): Add mutation tests for message_key

- src/olm/account/mod.rs
This fixes:
```
MISSED   src/olm/messages/pre_key.rs:81:9: replace PreKeyMessage::session_id -> String with String::new() in 0.9s build + 3.2s test
MISSED   src/olm/messages/pre_key.rs:81:9: replace PreKeyMessage::session_id -> String with "xyzzy".into() in 0.8s build + 2.8s test
```
Relates to: #78
> test(olm): Add mutation tests for pre_key

- src/olm/session/double_ratchet.rs
- src/olm/session/mod.rs
- src/olm/session/ratchet.rs
- src/olm/session/receiver_chain.rs
- src/olm/session/root_key.rs
Include the latest public ratchet keys in the debug output.
Fixes #125. Review commit-by-commit.
Question: does any of this need to be behind a feature flag? It's all public data so it feels like it's not a problem to retain or log it, but in theory I suppose there's a reduction in security due to keeping the parent ratchet key around.
> Log ratchet keys in `olm::Session::debug`

- .cargo/mutants.toml
- src/types/curve25519.rs
This fixes:
```
MISSED   src/types/curve25519.rs:58:9: replace Curve25519SecretKey::to_bytes -> Box<[u8; 32]> with Box::new([0; 32]) in 0.9s build + 3.0s test
MISSED   src/types/curve25519.rs:192:9: replace <impl Display for Curve25519PublicKey>::fmt -> std::fmt::Result with Ok(Default::default()) in 0.8s build + 3.1s test
MISSED   src/types/curve25519.rs:143:9: replace Curve25519PublicKey::to_vec -> Vec<u8> with vec![0] in 0.8s build + 3.1s test
MISSED   src/types/curve25519.rs:58:9: replace Curve25519SecretKey::to_bytes -> Box<[u8; 32]> with Box::new([1; 32]) in 0.9s build + 3.3s test
MISSED   src/types/curve25519.rs:143:9: replace Curve25519PublicKey::to_vec -> Vec<u8> with vec![1] in 0.8s build + 2.8s test
MISSED   src/types/curve25519.rs:143:9: replace Curve25519PublicKey::to_vec -> …
```
> test(types): Add mutation tests for curve25519

- src/olm/session/double_ratchet.rs
- src/olm/session/mod.rs
- src/olm/session/receiver_chain.rs
In order to help understand Olm decryption errors, let's keep track of the number of DH ratchet clicks, and log them as part of the debug output.
> Track the number of ratchet advances in the Olm Session, and include it in the debug output.

- src/types/ed25519.rs
This fixes:
```
MISSED   src/types/ed25519.rs:111:24: replace != with == in <impl Deserialize for ExpandedSecretKey>::deserialize in 0.8s build + 3.1s test
MISSED   src/types/ed25519.rs:153:9: replace Ed25519Keypair::expanded_secret_key -> Box<[u8; 64]> with Box::new([0; 64]) in 1.0s build + 3.7s test
MISSED   src/types/ed25519.rs:153:9: replace Ed25519Keypair::expanded_secret_key -> Box<[u8; 64]> with Box::new([1; 64]) in 0.9s build + 3.7s test
MISSED   src/types/ed25519.rs:209:9: replace Ed25519SecretKey::to_bytes -> Box<[u8; 32]> with Box::new([0; 32]) in 0.8s build + 2.8s test
MISSED   src/types/ed25519.rs:209:9: replace Ed25519SecretKey::to_bytes -> Box<[u8; 32]> with Box::new([1; 32]) in 0.9s build + 3.0s test
MISSED   src/types/ed25519.rs:214:9: replace Ed25519SecretKey::from_slice …
```
> test(types): Add mutation tests for ed25519

- src/olm/account/fallback_keys.rs
- src/olm/account/mod.rs
- src/olm/account/one_time_keys.rs
This fixes:
```
MISSED   src/olm/account/one_time_keys.rs:126:9: replace OneTimeKeys::is_secret_key_published -> bool with false in 0.9s build + 3.5s test
MISSED   src/olm/account/one_time_keys.rs:126:9: replace OneTimeKeys::is_secret_key_published -> bool with true in 0.9s build + 3.4s test
```
```
MISSED   src/olm/account/fallback_keys.rs:53:9: replace FallbackKey::published -> bool with false in 0.8s build + 3.0s test
MISSED   src/olm/account/fallback_keys.rs:70:9: replace FallbackKeys::mark_as_published with () in 0.8s build + 3.3s test
MISSED   src/olm/account/fallback_keys.rs:77:21: replace += with *= in FallbackKeys::generate_fallback_key in 0.8s build + 3.1s test
MISSED   src/olm/account/fallback_keys.rs:49:9: replace FallbackKey::mark_as_published with () in 0.8s build + 3.1s …
```
> test(olm): Add mutation tests for account

- .cargo/mutants.toml
- src/sas.rs
This fixes the following:
```
MISSED   src/sas.rs:152:9: replace SasBytes::emoji_indices -> [u8; 7] with [0; 7] in 0.8s build + 3.4s test
MISSED   src/sas.rs:152:9: replace SasBytes::emoji_indices -> [u8; 7] with [1; 7] in 0.9s build + 3.4s test
MISSED   src/sas.rs:160:9: replace SasBytes::decimals -> (u16, u16, u16) with (0, 0, 0) in 0.8s build + 3.1s test
MISSED   src/sas.rs:160:9: replace SasBytes::decimals -> (u16, u16, u16) with (0, 0, 1) in 0.8s build + 3.7s test
MISSED   src/sas.rs:160:9: replace SasBytes::decimals -> (u16, u16, u16) with (0, 1, 0) in 0.8s build + 3.0s test
MISSED   src/sas.rs:160:9: replace SasBytes::decimals -> (u16, u16, u16) with (0, 1, 1) in 0.8s build + 3.0s test
MISSED   src/sas.rs:160:9: replace SasBytes::decimals -> (u16, u16, u16) with (1, 0, 0) in 0.8s …
```
> test(sas): Add mutation tests

- .cargo/mutants.toml
- src/olm/messages/mod.rs
- src/olm/session/chain_key.rs
- src/olm/session/mod.rs
- src/olm/session/ratchet.rs
- src/olm/session_config.rs
This fixes the remaining mutation tests under `src/olm`:
```
MISSED   src/olm/account/one_time_keys.rs:45:42: replace * with + in 0.8s build + 3.2s test
MISSED   src/olm/messages/mod.rs:99:9: replace OlmMessage::message -> &[u8] with Vec::leak(Vec::new()) in 0.8s build + 3.2s test
MISSED   src/olm/messages/mod.rs:99:9: replace OlmMessage::message -> &[u8] with Vec::leak(vec![0]) in 0.8s build + 2.9s test
MISSED   src/olm/messages/mod.rs:99:9: replace OlmMessage::message -> &[u8] with Vec::leak(vec![1]) in 0.8s build + 3.1s test
MISSED   src/olm/session/chain_key.rs:112:9: replace ChainKey::index -> u64 with 0 in 0.8s build + 3.0s test
MISSED   src/olm/session/chain_key.rs:112:9: replace ChainKey::index -> u64 with 1 in 0.8s build + 2.9s test
MISSED   src/olm/session/mod.rs:226:9: replace …
```
> test(olm): Add remaining mutation tests

- src/megolm/group_session.rs
- src/megolm/inbound_group_session.rs
- src/olm/session/mod.rs
This is an attempt at fixing the latest clippy warnings. The diff is quite large but in essence, I only moved the `from_libolm_pickle` methods into a separate module in the same file, broke out their contents and updated the imports.
I'm not sure if this is the best way but it appears to work and doesn't require using a myriad of `#[cfg(feature = "libolm-compat")]` annotations.
```
error: non-local `impl` definition, they should be avoided as they go against expectation
--> src/megolm/group_session.rs:165:9
|
165 | /         impl TryFrom<Pickle> for GroupSession {
166 | |             type Error = crate::LibolmPickleError;
167 | |
168 | |             fn try_from(pickle: Pickle) -> Result<Self, Self::Error> {
...   |
177 | |             }
178 | |         }
| |_________^
|
= help: move this …
```
> chore: Fix clippy warnings about non-local impl definition

- src/secure_channel/messages.rs
- src/secure_channel/mod.rs
For the attention of @dkasak.
Implement changes from matrix-org/matrix-spec-proposals@aa37af9
> MSC4108 secure channel split encryption keys and monotonic nonces

- .cargo/mutants.toml
- src/cipher/mod.rs
This fixes the following:
```
MISSED   src/cipher/mod.rs:146:29: replace < with == in Cipher::decrypt_pickle in 0.9s build + 3.1s test
MISSED   src/cipher/mod.rs:146:50: replace + with * in Cipher::decrypt_pickle in 0.9s build + 3.1s test
MISSED   src/cipher/mod.rs:146:50: replace + with - in Cipher::decrypt_pickle in 0.9s build + 3.1s test
MISSED   src/cipher/mod.rs:175:9: replace Cipher::verify_truncated_mac -> Result<(), MacError> with Ok(()) in 0.9s build + 3.5s test
```
Relates to: #78
> test(cipher): Add mutation tests

- .cargo/mutants.toml
- .github/workflows/ci.yml
- src/megolm/group_session.rs
- src/megolm/inbound_group_session.rs
- src/megolm/message.rs
- src/megolm/mod.rs
- src/megolm/ratchet.rs
- src/megolm/session_config.rs
This fixes the following issues:
```
MISSED   src/megolm/group_session.rs:80:9: replace GroupSession::session_config -> SessionConfig with Default::default() in 0.8s build + 3.1s test
MISSED   src/megolm/inbound_group_session.rs:289:47: replace < with == in InboundGroupSession::find_ratchet in 0.8s build + 3.1s test
MISSED   src/megolm/inbound_group_session.rs:302:9: replace InboundGroupSession::verify_mac -> Result<(), DecryptionError> with Ok(()) in 1.0s build + 3.1s test
MISSED   src/megolm/message.rs:133:9: replace MegolmMessage::add_signature -> Result<(), SignatureError> with Ok(()) in 0.8s build + 3.7s test
MISSED   src/megolm/message.rs:282:42: replace + with - in <impl TryFrom for MegolmMessage>::try_from in 0.8s build + 3.0s test
MISSED   src/megolm/message.rs:50:54: replace + …
```
> test(megolm): Add mutation tests

- .github/workflows/ci.yml
Depends on: #142
Fixes: #78
This largely follows https://mutants.rs/ci.html and sets up incremental mutation tests on pull requests and full mutation tests on pushes. The full suite takes about half an hour on my laptop.
> test: Enable mutation tests on CI

- CHANGELOG.md
- Cargo.toml
Apparently keywords need to have less than 20 characters.
> chore: Remove the end-to-end-encryption keyword

- Cargo.toml
- src/ecies/messages.rs
- src/ecies/mod.rs
- src/lib.rs
- src/olm/account/mod.rs
This commits adds a Elliptic Curve Encryption Scheme, this scheme can be used in ephemeral situations where a full 3DH-based Olm session might be overkill or too hard to set up.
The canonical example where this can be used is the QR code login feature in Matrix[^1].
Co-authored-by: Denis Kasak <dkasak@termina.org.uk>
Co-authored-by: Hugh Nimmo-Smith <hughns@users.noreply.github.com>
[^1]: https://github.com/matrix-org/matrix-spec-proposals/pull/4108
> Add an Elliptic Curve Encryption Scheme

- README.md
In a chat with @ara4n yesterday I learnt that the legacy backup has actually been implemented in [matrix-sdk-crypto](https://github.com/matrix-org/matrix-rust-sdk/tree/main/crates/matrix-sdk-crypto/src/backups) and isn't planned to be added here anymore. I suppose [MSC4048](https://github.com/matrix-org/matrix-spec-proposals/pull/4048) will be implemented there, too, then which is why I have removed its reference as well.
> Clarify status of backup implementation

- Cargo.toml
- src/megolm/session_keys.rs
- src/types/ed25519.rs
- src/types/mod.rs
This patch fixes a security issue around a side-channel vulnerability[^1] when decoding secret key material using Base64.
In some circumstances an attacker can obtain information about secret key material via a controlled-channel and side-channel attack.
This patch avoids the side-channel by switching to the base64ct crate for the encoding, and more importantly, the decoding of secret key material.
[^1]: https://arxiv.org/abs/2108.04600
> fix: Use a constant-time Base64 encoder for secret key material

- CONTRIBUTING.md
The Matrix.org Foundation is rolling out this DCO across all public repositories in its namespace. Of note, this DCO does not require the use of "real" or "legally identifiable" names.
> Add a Developer Certificate of Origin

- Cargo.toml
The pkcs7 crate has been deprecated[^1], the authors recommend us to switch to the block_padding crate instead.
Incidentally we're already using the block_padding crate for our pkcs7 needs as that one is re-exported by the AES crate. This means that the pkcs7 crate is already an unused dependency and we can just remove it.
This has been confirmed by cargo-udeps[^2] as well.
This closes: #162. 
[^1]: https://docs.rs/pkcs7/0.4.1/pkcs7/index.html#-deprecated-
[^2]: https://github.com/est31/cargo-udeps
> refactor: Remove the pkcs7 crate from the list of dependencies

- afl/README.md
It seems like it at some point had been renamed to `cargo-afl`.
It seems to at least with `afl/olm-message-decoding` still work.
However the new cfg linting in rust is a bit unhappy about the fuzzing cfg flags:
```
warning: unexpected `cfg` condition name: `fuzzing`
--> src/main.rs:29:11
|
29 | #[cfg(not(fuzzing))]
|           ^^^^^^^
|
= help: consider using a Cargo feature instead
= help: or consider adding in `Cargo.toml` the `check-cfg` lint config for the lint:
[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(fuzzing)'] }
= help: or consider adding `println!("cargo::rustc-check-cfg=cfg(fuzzing)");` to the top of the `build.rs`
= note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html> for more information about checking conditional …
```
> Update the afl binary install command to the correct package

- src/cipher/key.rs
- src/ecies/mod.rs
- src/lib.rs
- src/megolm/group_session.rs
- src/megolm/inbound_group_session.rs
- src/megolm/message.rs
- src/megolm/mod.rs
- src/megolm/ratchet.rs
- src/megolm/session_config.rs
- src/olm/account/fallback_keys.rs
- src/olm/account/mod.rs
- src/olm/account/one_time_keys.rs
- src/olm/messages/message.rs
- src/olm/messages/mod.rs
- src/olm/messages/pre_key.rs
- src/olm/session/chain_key.rs
- src/olm/session/double_ratchet.rs
- src/olm/session/message_key.rs
- src/olm/session/mod.rs
- src/olm/session/ratchet.rs
- src/olm/session/receiver_chain.rs
- src/olm/session/root_key.rs
- src/olm/session_config.rs
- src/sas.rs
- src/types/curve25519.rs
- src/types/ed25519.rs
- src/utilities/mod.rs
This is based on the feedback given by the clippy [`missing_const_for_fn`](https://rust-lang.github.io/rust-clippy/master/index.html#/missing_const_for_fn) lint, which is still in nursery.
In a very non-scientific comparison, the `olm-message-decoding` afl fuzzer runs with ~0.5k to ~1k more executions per second on my PC.
I did not verify if any bindings rely on these to be not `const`. However, the test suite returned that everything is ok.
Signed-Off-By: MTRNord <git@nordgedanken.dev>
> Apply const keyword to various methods

- CONTRIBUTING.md
- cliff.toml
- src/ecies/mod.rs
This PR modifies the way `git-cliff` parses commits and produces changelog entries, please take a look at the updated `CONTRIBUTING.md` file for more info.
In short, it allows us to write a commit like this:
```
fix: Use a constant-time Base64 encoder for secret key material
This patch fixes a security issue around a side-channel vulnerability[1]
when decoding secret key material using Base64.
In some circumstances an attacker can obtain information about secret
secret key material via a controlled-channel and side-channel attack.
This patch avoids the side-channel by switching to the base64ct crate
for the encoding, and more importantly, the decoding of secret key
material.
Security-Impact: Low
CVE: CVE-2024-40640
GitHub-Advisory: GHSA-j8cm-g7r6-hfpq
Changelog: Use a constant-time Base64 …
```
> Allow the usage of git-trailers for changelog messages

- src/olm/account/mod.rs
- src/olm/messages/mod.rs
All the other primitives are dealing directly with bytes I believe so this PR aligns to that.
Signed-off-by: Mathieu Velten <mathieu@velten.xyz>
> feat(api)!: Remove base64 expectation for messages in the API

- .editorconfig
- .vscode/settings.json
The editorconfig and vscode settings for rust-analyzer have been established as cross-editor settings. At least nvim and vscode itself support them and people often times have trouble with our cargo fmt settings which require nightly.
This way, if a supported editor is used, no additional setup is required by the contributor.
> Add an editorconfig and vscode settings

- .github/workflows/ci.yml
- Cargo.toml
- src/cipher/key.rs
- src/cipher/mod.rs
- src/lib.rs
- src/olm/messages/pre_key.rs
- src/olm/session/message_key.rs
- src/pk_encryption.rs
A review commit-by-commit is advised, there are a couple of unrelated commits here to make the CI happy.
The meat of the PR is the libolm's PKEncryption support, for more info please take a look at the commit message which adds this functionality. Please note that the commit message assumes that we're going to merge #165.
> Bug-for bug compatibility with libolm's PkEncryption support

- src/olm/account/mod.rs
- src/olm/session/mod.rs
These structs contain private key material so they shouldn't have Debug implementations, even unused ones.
This closes: #70.
> refactor: Remove Debug implementations for the libolm compat structs

- .github/workflows/ci.yml
- src/cipher/key.rs
- src/cipher/mod.rs
- src/megolm/ratchet.rs
- src/olm/account/mod.rs
- src/olm/account/one_time_keys.rs
- src/olm/session/double_ratchet.rs
- src/sas.rs
- src/types/ed25519.rs
> fix: Fix the compilation when the default features are disabled

- Cargo.toml
There's no reason to constify every method we have that might be constified so let's disable the lint.
> chore: Disable the const function lint

- .deny.toml
- src/olm/account/mod.rs
- src/olm/session/mod.rs
This was necessary because olm-sys started to fail to build because of the minimally required CMake version needed to be bumped.
> chore: Allow the usage of a git source for olm-sys
